name: ci
on:
  push:
    branches:
      - feature/*
      - main
  pull_request:
    branches: [ main ]
defaults:
  run:
    working-directory: ms-assessments/functions
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn
        name: Get dependencies
      - run: yarn build
        name: Build
