name: ci
on:
  push:
    branches:
      - feature/*
      - main
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: yarn
        name: Get dependencies
        working-directory: ms-assessments/functions
      - run: yarn build
        name: Build
        working-directory: ms-assessments/functions
      - name: Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@4.0.0
        with:
          # API project token to retrieve your remote Codacy configuration for the project being analyzed
          project-token: ${{ secrets.CODACY_TOKEN }}
          directory: ms-assessments/functions
